### ISSUE TITLE
Rapidly maximizing and minimizing results in Plume becoming unresponsive

### ISSUE THREAD

**Issue by evanmohr** [nuttyartist/plume-public#3]
App Version: Plume 0.9.2 Appimage
OS Version: OpenSUSE Tumbleweed
Desktop: Plasma 6.0.4 Wayland

Video: 

https://github.com/nuttyartist/plume-public/assets/80165419/de5720f4-c997-4e4f-8f0c-7767ae7f27da

**Comment by nuttyartist** [comment]
This looks very similar to a previous bug (https://bugreports.qt.io/browse/QTBUG-115459) in Qt that supposedly got resolved in Qt 6.7.0 (that the AppImage uses).

**Comment by nuttyartist** [comment]
If you do it slowly, it doesn't result in this bug?

**Comment by evanmohr** [comment]
It still happens if I wait around 5 seconds between toggling
